import type { NextPage } from 'next';
import Head from 'next/head';

import InvoicesHeader from '../components/invoices-header/InvoicesHeader';
import { Button } from '../components/UI/button/ButtonStyles';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/favicon-32x32.png" />
      </Head>

      <InvoicesHeader total={0} />
    </>
  );
};

export default Home;
